export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'


export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST'
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS'
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL'
export const ORDER_DELIVERED_RESET = 'ORDER_DELIVERED_RESET'

export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST'
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS'
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL'
export const MY_ORDERS_RESET = 'MY_ORDERS_RESET'

export const ALLORDER_LIST_REQUEST = 'ALLORDER_LIST_REQUEST'
export const ALLORDER_LIST_SUCCESS = 'ALLORDER_LIST_SUCCESS'
export const ALLORDER_LIST_FAIL = 'ALLORDER_LIST_FAIL'